// Country-specific invoice configuration for 20 countries
// Each country defines its tax system, rates, required fields, labels, and print format

const COUNTRY_CONFIGS = {
  // ─── INDIA ────────────────────────────────────────────────────────────
  IN: {
    code: 'IN',
    name: 'India',
    currency: 'INR',
    currencySymbol: '₹',
    currencyLocale: 'en-IN',
    useExistingForms: true, // Use existing SalesInvoiceModal / PurchaseBillModal
    taxSystem: 'GST',
    // India config is handled by existing modals — no further config needed
  },

  // ─── UNITED STATES ────────────────────────────────────────────────────
  US: {
    code: 'US',
    name: 'United States',
    currency: 'USD',
    currencySymbol: '$',
    currencyLocale: 'en-US',
    taxSystem: 'Sales Tax',
    taxIdLabel: 'EIN (Employer Identification Number)',
    taxIdPlaceholder: 'e.g. 12-3456789',
    taxIdMaxLength: 10,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'Sales Tax Invoice',
    taxRates: [
      { label: 'No Tax', rate: 0 },
      { label: 'State Sales Tax', rate: null, customRate: true },
    ],
    defaultTaxRate: 0,
    supportsCustomTaxRate: true,
    customTaxRateLabel: 'Sales Tax %',
    customTaxRateHint: 'Varies by state (0% – 10.25%)',
    taxBreakdown: 'single', // single line for total tax
    regionType: 'state',
    regionLabel: 'State',
    regions: [
      'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
      'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
      'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
      'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
      'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
      'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
      'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
      'Wisconsin', 'Wyoming', 'District of Columbia',
    ],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId', 'region'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Vendor',
    printTitle: { simple: 'INVOICE', tax: 'SALES TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice #',
      invoiceDate: 'Invoice Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Rate',
      amount: 'Amount',
      subtotal: 'Subtotal',
      discount: 'Discount',
      taxLine: 'Sales Tax',
      total: 'Total',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── UNITED KINGDOM ───────────────────────────────────────────────────
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    currency: 'GBP',
    currencySymbol: '£',
    currencyLocale: 'en-GB',
    taxSystem: 'VAT',
    taxIdLabel: 'VAT Registration Number',
    taxIdPlaceholder: 'e.g. GB123456789',
    taxIdMaxLength: 14,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'VAT Invoice',
    taxRates: [
      { label: 'Standard (20%)', rate: 20 },
      { label: 'Reduced (5%)', rate: 5 },
      { label: 'Zero-rated (0%)', rate: 0 },
    ],
    defaultTaxRate: 20,
    supportsCustomTaxRate: false,
    taxBreakdown: 'per_rate', // show breakdown per VAT rate
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName', 'firmAddress'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'companyNumber', 'bankDetails'],
    extraFields: [
      { key: 'companyNumber', label: 'Company Registration Number', placeholder: 'e.g. 12345678', maxLength: 8 },
    ],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'VAT INVOICE' },
    printLabels: {
      billTo: 'Invoice To',
      shipTo: 'Deliver To',
      invoiceNo: 'Invoice Number',
      invoiceDate: 'Date of Issue',
      dueDate: 'Due Date',
      taxPoint: 'Tax Point',
      description: 'Description',
      quantity: 'Quantity',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Net Total',
      discount: 'Discount',
      taxLine: 'VAT',
      total: 'Total Due',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
      vatSummary: 'VAT Summary',
    },
  },

  // ─── UNITED ARAB EMIRATES ─────────────────────────────────────────────
  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    currency: 'AED',
    currencySymbol: 'د.إ',
    currencyLocale: 'en-AE',
    taxSystem: 'VAT',
    taxIdLabel: 'TRN (Tax Registration Number)',
    taxIdPlaceholder: 'e.g. 100123456700003',
    taxIdMaxLength: 15,
    simpleInvoiceLabel: 'Simplified Tax Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'Standard (5%)', rate: 5 },
      { label: 'Zero-rated (0%)', rate: 0 },
      { label: 'Exempt', rate: 0, exempt: true },
    ],
    defaultTaxRate: 5,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: 'emirate',
    regionLabel: 'Emirate',
    regions: ['Abu Dhabi', 'Dubai', 'Sharjah', 'Ajman', 'Umm Al Quwain', 'Ras Al Khaimah', 'Fujairah'],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'SIMPLIFIED TAX INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice No.',
      invoiceDate: 'Date of Supply',
      dueDate: 'Due Date',
      description: 'Description of Goods/Services',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount (AED)',
      subtotal: 'Subtotal',
      discount: 'Discount',
      taxLine: 'VAT (5%)',
      total: 'Total (incl. VAT)',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── CANADA ───────────────────────────────────────────────────────────
  CA: {
    code: 'CA',
    name: 'Canada',
    currency: 'CAD',
    currencySymbol: 'C$',
    currencyLocale: 'en-CA',
    taxSystem: 'GST/HST',
    taxIdLabel: 'Business Number (BN)',
    taxIdPlaceholder: 'e.g. 123456789RT0001',
    taxIdMaxLength: 15,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'HST 13% (ON, NB, NL)', rate: 13 },
      { label: 'HST 15% (NS, PE)', rate: 15 },
      { label: 'GST 5%', rate: 5 },
      { label: 'Zero-rated (0%)', rate: 0 },
    ],
    defaultTaxRate: 5,
    supportsCustomTaxRate: true,
    customTaxRateLabel: 'Combined Tax %',
    customTaxRateHint: 'GST 5% + PST varies by province (0–10%)',
    taxBreakdown: 'single',
    regionType: 'province',
    regionLabel: 'Province / Territory',
    regions: [
      'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador',
      'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island',
      'Quebec', 'Saskatchewan', 'Yukon',
    ],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId', 'region'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Vendor',
    printTitle: { simple: 'INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice #',
      invoiceDate: 'Invoice Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Rate',
      amount: 'Amount',
      subtotal: 'Subtotal',
      discount: 'Discount',
      taxLine: 'Tax',
      total: 'Total',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── AUSTRALIA ────────────────────────────────────────────────────────
  AU: {
    code: 'AU',
    name: 'Australia',
    currency: 'AUD',
    currencySymbol: 'A$',
    currencyLocale: 'en-AU',
    taxSystem: 'GST',
    taxIdLabel: 'ABN (Australian Business Number)',
    taxIdPlaceholder: 'e.g. 51 824 753 556',
    taxIdMaxLength: 14,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'GST (10%)', rate: 10 },
      { label: 'GST-free (0%)', rate: 0 },
    ],
    defaultTaxRate: 10,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: 'state',
    regionLabel: 'State / Territory',
    regions: [
      'Australian Capital Territory', 'New South Wales', 'Northern Territory',
      'Queensland', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia',
    ],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice Number',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal (excl. GST)',
      discount: 'Discount',
      taxLine: 'GST',
      total: 'Total (incl. GST)',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── GERMANY ──────────────────────────────────────────────────────────
  DE: {
    code: 'DE',
    name: 'Germany',
    currency: 'EUR',
    currencySymbol: '€',
    currencyLocale: 'de-DE',
    taxSystem: 'VAT (USt)',
    taxIdLabel: 'USt-IdNr. (VAT ID)',
    taxIdPlaceholder: 'e.g. DE123456789',
    taxIdMaxLength: 14,
    simpleInvoiceLabel: 'Rechnung (Invoice)',
    taxInvoiceLabel: 'Rechnung mit USt (VAT Invoice)',
    taxRates: [
      { label: 'Standard (19%)', rate: 19 },
      { label: 'Reduced (7%)', rate: 7 },
      { label: 'Tax-free (0%)', rate: 0 },
    ],
    defaultTaxRate: 19,
    supportsCustomTaxRate: false,
    taxBreakdown: 'per_rate',
    regionType: 'state',
    regionLabel: 'Bundesland (State)',
    regions: [
      'Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg',
      'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen',
      'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen',
    ],
    requiredFieldsSimple: ['firmName', 'firmAddress'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'steuernummer', 'bankDetails'],
    extraFields: [
      { key: 'steuernummer', label: 'Steuernummer (Tax Number)', placeholder: 'e.g. 12/345/67890', maxLength: 16 },
    ],
    customerLabel: 'Kunde (Customer)',
    vendorLabel: 'Lieferant (Supplier)',
    printTitle: { simple: 'RECHNUNG', tax: 'RECHNUNG' },
    printLabels: {
      billTo: 'Rechnungsempfänger',
      shipTo: 'Lieferadresse',
      invoiceNo: 'Rechnungsnummer',
      invoiceDate: 'Rechnungsdatum',
      dueDate: 'Fälligkeitsdatum',
      deliveryDate: 'Lieferdatum',
      description: 'Bezeichnung',
      quantity: 'Menge',
      rate: 'Einzelpreis',
      amount: 'Betrag',
      subtotal: 'Nettobetrag',
      discount: 'Rabatt',
      taxLine: 'USt.',
      total: 'Gesamtbetrag',
      amountDue: 'Zahlungsbetrag',
      paymentTerms: 'Zahlungsbedingungen',
      notes: 'Hinweise',
    },
  },

  // ─── FRANCE ───────────────────────────────────────────────────────────
  FR: {
    code: 'FR',
    name: 'France',
    currency: 'EUR',
    currencySymbol: '€',
    currencyLocale: 'fr-FR',
    taxSystem: 'VAT (TVA)',
    taxIdLabel: 'Numéro TVA intracommunautaire',
    taxIdPlaceholder: 'e.g. FR12345678901',
    taxIdMaxLength: 15,
    simpleInvoiceLabel: 'Facture',
    taxInvoiceLabel: 'Facture avec TVA',
    taxRates: [
      { label: 'Normal (20%)', rate: 20 },
      { label: 'Intermédiaire (10%)', rate: 10 },
      { label: 'Réduit (5.5%)', rate: 5.5 },
      { label: 'Super-réduit (2.1%)', rate: 2.1 },
    ],
    defaultTaxRate: 20,
    supportsCustomTaxRate: false,
    taxBreakdown: 'per_rate',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName', 'firmAddress'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'siret', 'bankDetails'],
    extraFields: [
      { key: 'siret', label: 'SIRET', placeholder: 'e.g. 362 521 879 00034', maxLength: 17 },
    ],
    customerLabel: 'Client',
    vendorLabel: 'Fournisseur',
    printTitle: { simple: 'FACTURE', tax: 'FACTURE' },
    printLabels: {
      billTo: 'Facturer à',
      shipTo: 'Livrer à',
      invoiceNo: 'Numéro de facture',
      invoiceDate: 'Date de facture',
      dueDate: 'Date d\'échéance',
      description: 'Désignation',
      quantity: 'Qté',
      rate: 'Prix unitaire',
      amount: 'Montant HT',
      subtotal: 'Total HT',
      discount: 'Remise',
      taxLine: 'TVA',
      total: 'Total TTC',
      amountDue: 'Net à payer',
      paymentTerms: 'Conditions de paiement',
      notes: 'Mentions légales',
    },
  },

  // ─── SINGAPORE ────────────────────────────────────────────────────────
  SG: {
    code: 'SG',
    name: 'Singapore',
    currency: 'SGD',
    currencySymbol: 'S$',
    currencyLocale: 'en-SG',
    taxSystem: 'GST',
    taxIdLabel: 'GST Registration Number',
    taxIdPlaceholder: 'e.g. M90000001A',
    taxIdMaxLength: 10,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'GST (9%)', rate: 9 },
      { label: 'Zero-rated (0%)', rate: 0 },
      { label: 'Exempt', rate: 0, exempt: true },
    ],
    defaultTaxRate: 9,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'uen', 'bankDetails'],
    extraFields: [
      { key: 'uen', label: 'UEN (Unique Entity Number)', placeholder: 'e.g. 201912345A', maxLength: 10 },
    ],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice No.',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal',
      discount: 'Discount',
      taxLine: 'GST (9%)',
      total: 'Total',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── SAUDI ARABIA ─────────────────────────────────────────────────────
  SA: {
    code: 'SA',
    name: 'Saudi Arabia',
    currency: 'SAR',
    currencySymbol: 'SAR',
    currencyLocale: 'en-SA',
    taxSystem: 'VAT',
    taxIdLabel: 'VAT Registration Number',
    taxIdPlaceholder: 'e.g. 300000000000003',
    taxIdMaxLength: 15,
    simpleInvoiceLabel: 'Simplified Tax Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'Standard (15%)', rate: 15 },
      { label: 'Zero-rated (0%)', rate: 0 },
      { label: 'Exempt', rate: 0, exempt: true },
    ],
    defaultTaxRate: 15,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'crNumber', 'bankDetails'],
    extraFields: [
      { key: 'crNumber', label: 'CR Number (Commercial Registration)', placeholder: 'e.g. 1010123456', maxLength: 10 },
    ],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'SIMPLIFIED TAX INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice No.',
      invoiceDate: 'Date of Supply',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount (SAR)',
      subtotal: 'Total (excl. VAT)',
      discount: 'Discount',
      taxLine: 'VAT (15%)',
      total: 'Total (incl. VAT)',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── JAPAN ────────────────────────────────────────────────────────────
  JP: {
    code: 'JP',
    name: 'Japan',
    currency: 'JPY',
    currencySymbol: '¥',
    currencyLocale: 'ja-JP',
    taxSystem: 'Consumption Tax',
    taxIdLabel: 'Registration Number (適格請求書発行事業者)',
    taxIdPlaceholder: 'e.g. T1234567890123',
    taxIdMaxLength: 14,
    simpleInvoiceLabel: '請求書 (Invoice)',
    taxInvoiceLabel: '適格請求書 (Qualified Invoice)',
    taxRates: [
      { label: 'Standard (10%)', rate: 10 },
      { label: 'Reduced (8%)', rate: 8 },
    ],
    defaultTaxRate: 10,
    supportsCustomTaxRate: false,
    taxBreakdown: 'per_rate',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: '請求書 / INVOICE', tax: '適格請求書 / QUALIFIED INVOICE' },
    printLabels: {
      billTo: '請求先 / Bill To',
      shipTo: '納品先 / Ship To',
      invoiceNo: '請求書番号 / Invoice No.',
      invoiceDate: '発行日 / Date',
      dueDate: '支払期限 / Due Date',
      description: '品名 / Description',
      quantity: '数量 / Qty',
      rate: '単価 / Unit Price',
      amount: '金額 / Amount',
      subtotal: '小計 / Subtotal',
      discount: '値引 / Discount',
      taxLine: '消費税 / Tax',
      total: '合計 / Total',
      amountDue: 'お支払い額 / Amount Due',
      paymentTerms: '支払条件 / Payment Terms',
      notes: '備考 / Notes',
    },
  },

  // ─── SOUTH KOREA ──────────────────────────────────────────────────────
  KR: {
    code: 'KR',
    name: 'South Korea',
    currency: 'KRW',
    currencySymbol: '₩',
    currencyLocale: 'ko-KR',
    taxSystem: 'VAT',
    taxIdLabel: 'Business Registration Number (사업자등록번호)',
    taxIdPlaceholder: 'e.g. 123-45-67890',
    taxIdMaxLength: 12,
    simpleInvoiceLabel: '계산서 (Invoice)',
    taxInvoiceLabel: '세금계산서 (Tax Invoice)',
    taxRates: [
      { label: 'Standard (10%)', rate: 10 },
      { label: 'Zero-rated (0%)', rate: 0 },
    ],
    defaultTaxRate: 10,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: '계산서 / INVOICE', tax: '세금계산서 / TAX INVOICE' },
    printLabels: {
      billTo: '공급받는자 / Bill To',
      shipTo: 'Ship To',
      invoiceNo: '일련번호 / Invoice No.',
      invoiceDate: '작성일 / Date',
      dueDate: '지급기일 / Due Date',
      description: '품목 / Description',
      quantity: '수량 / Qty',
      rate: '단가 / Unit Price',
      amount: '공급가액 / Amount',
      subtotal: '합계금액 / Subtotal',
      discount: '할인 / Discount',
      taxLine: '부가세 / VAT',
      total: '총액 / Total',
      amountDue: '청구금액 / Amount Due',
      paymentTerms: '결제조건 / Terms',
      notes: '비고 / Notes',
    },
  },

  // ─── NETHERLANDS ──────────────────────────────────────────────────────
  NL: {
    code: 'NL',
    name: 'Netherlands',
    currency: 'EUR',
    currencySymbol: '€',
    currencyLocale: 'nl-NL',
    taxSystem: 'VAT (BTW)',
    taxIdLabel: 'BTW-nummer (VAT Number)',
    taxIdPlaceholder: 'e.g. NL123456789B01',
    taxIdMaxLength: 14,
    simpleInvoiceLabel: 'Factuur (Invoice)',
    taxInvoiceLabel: 'BTW-Factuur (VAT Invoice)',
    taxRates: [
      { label: 'Standard (21%)', rate: 21 },
      { label: 'Reduced (9%)', rate: 9 },
      { label: 'Zero-rated (0%)', rate: 0 },
    ],
    defaultTaxRate: 21,
    supportsCustomTaxRate: false,
    taxBreakdown: 'per_rate',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName', 'firmAddress'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'kvkNumber', 'bankDetails'],
    extraFields: [
      { key: 'kvkNumber', label: 'KVK Number (Chamber of Commerce)', placeholder: 'e.g. 12345678', maxLength: 8 },
    ],
    customerLabel: 'Klant (Customer)',
    vendorLabel: 'Leverancier (Supplier)',
    printTitle: { simple: 'FACTUUR', tax: 'BTW-FACTUUR' },
    printLabels: {
      billTo: 'Factureren aan',
      shipTo: 'Afleveradres',
      invoiceNo: 'Factuurnummer',
      invoiceDate: 'Factuurdatum',
      dueDate: 'Vervaldatum',
      description: 'Omschrijving',
      quantity: 'Aantal',
      rate: 'Prijs',
      amount: 'Bedrag',
      subtotal: 'Subtotaal',
      discount: 'Korting',
      taxLine: 'BTW',
      total: 'Totaal',
      amountDue: 'Te betalen',
      paymentTerms: 'Betalingsvoorwaarden',
      notes: 'Opmerkingen',
    },
  },

  // ─── BRAZIL ───────────────────────────────────────────────────────────
  BR: {
    code: 'BR',
    name: 'Brazil',
    currency: 'BRL',
    currencySymbol: 'R$',
    currencyLocale: 'pt-BR',
    taxSystem: 'Tax (ICMS/ISS/IPI)',
    taxIdLabel: 'CNPJ',
    taxIdPlaceholder: 'e.g. 12.345.678/0001-90',
    taxIdMaxLength: 18,
    simpleInvoiceLabel: 'Fatura (Invoice)',
    taxInvoiceLabel: 'Nota Fiscal (Tax Invoice)',
    taxRates: [
      { label: 'ISS Services (2–5%)', rate: null, customRate: true },
      { label: 'ICMS Goods (varies)', rate: null, customRate: true },
      { label: 'No Tax (0%)', rate: 0 },
    ],
    defaultTaxRate: 0,
    supportsCustomTaxRate: true,
    customTaxRateLabel: 'Tax %',
    customTaxRateHint: 'ISS 2–5%, ICMS 7–25% depending on state',
    taxBreakdown: 'single',
    regionType: 'state',
    regionLabel: 'Estado (State)',
    regions: [
      'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará', 'Distrito Federal',
      'Espírito Santo', 'Goiás', 'Maranhão', 'Mato Grosso', 'Mato Grosso do Sul',
      'Minas Gerais', 'Pará', 'Paraíba', 'Paraná', 'Pernambuco', 'Piauí',
      'Rio de Janeiro', 'Rio Grande do Norte', 'Rio Grande do Sul', 'Rondônia',
      'Roraima', 'Santa Catarina', 'São Paulo', 'Sergipe', 'Tocantins',
    ],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId', 'region'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    extraFields: [
      { key: 'inscricaoEstadual', label: 'Inscrição Estadual', placeholder: 'State Registration', maxLength: 20 },
    ],
    customerLabel: 'Cliente (Customer)',
    vendorLabel: 'Fornecedor (Supplier)',
    printTitle: { simple: 'FATURA', tax: 'NOTA FISCAL' },
    printLabels: {
      billTo: 'Faturar para',
      shipTo: 'Entregar em',
      invoiceNo: 'Número da Fatura',
      invoiceDate: 'Data de Emissão',
      dueDate: 'Vencimento',
      description: 'Descrição',
      quantity: 'Qtde',
      rate: 'Valor Unitário',
      amount: 'Valor Total',
      subtotal: 'Subtotal',
      discount: 'Desconto',
      taxLine: 'Imposto',
      total: 'Total',
      amountDue: 'Valor a Pagar',
      paymentTerms: 'Condições de Pagamento',
      notes: 'Observações',
    },
  },

  // ─── SOUTH AFRICA ─────────────────────────────────────────────────────
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    currency: 'ZAR',
    currencySymbol: 'R',
    currencyLocale: 'en-ZA',
    taxSystem: 'VAT',
    taxIdLabel: 'VAT Registration Number',
    taxIdPlaceholder: 'e.g. 4012345678',
    taxIdMaxLength: 10,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'Standard (15%)', rate: 15 },
      { label: 'Zero-rated (0%)', rate: 0 },
      { label: 'Exempt', rate: 0, exempt: true },
    ],
    defaultTaxRate: 15,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: 'province',
    regionLabel: 'Province',
    regions: [
      'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo',
      'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape',
    ],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice No.',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal (excl. VAT)',
      discount: 'Discount',
      taxLine: 'VAT (15%)',
      total: 'Total (incl. VAT)',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── NEW ZEALAND ──────────────────────────────────────────────────────
  NZ: {
    code: 'NZ',
    name: 'New Zealand',
    currency: 'NZD',
    currencySymbol: 'NZ$',
    currencyLocale: 'en-NZ',
    taxSystem: 'GST',
    taxIdLabel: 'GST Number',
    taxIdPlaceholder: 'e.g. 12-345-678',
    taxIdMaxLength: 11,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'GST (15%)', rate: 15 },
      { label: 'Zero-rated (0%)', rate: 0 },
    ],
    defaultTaxRate: 15,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'nzbn', 'bankDetails'],
    extraFields: [
      { key: 'nzbn', label: 'NZBN (NZ Business Number)', placeholder: 'e.g. 9429012345678', maxLength: 13 },
    ],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice Number',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal (excl. GST)',
      discount: 'Discount',
      taxLine: 'GST (15%)',
      total: 'Total (incl. GST)',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── IRELAND ──────────────────────────────────────────────────────────
  IE: {
    code: 'IE',
    name: 'Ireland',
    currency: 'EUR',
    currencySymbol: '€',
    currencyLocale: 'en-IE',
    taxSystem: 'VAT',
    taxIdLabel: 'VAT Registration Number',
    taxIdPlaceholder: 'e.g. IE1234567T',
    taxIdMaxLength: 11,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'VAT Invoice',
    taxRates: [
      { label: 'Standard (23%)', rate: 23 },
      { label: 'Reduced (13.5%)', rate: 13.5 },
      { label: 'Second Reduced (9%)', rate: 9 },
      { label: 'Zero-rated (0%)', rate: 0 },
    ],
    defaultTaxRate: 23,
    supportsCustomTaxRate: false,
    taxBreakdown: 'per_rate',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName', 'firmAddress'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'VAT INVOICE' },
    printLabels: {
      billTo: 'Invoice To',
      shipTo: 'Deliver To',
      invoiceNo: 'Invoice Number',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Net Total',
      discount: 'Discount',
      taxLine: 'VAT',
      total: 'Gross Total',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
      vatSummary: 'VAT Summary',
    },
  },

  // ─── HONG KONG ────────────────────────────────────────────────────────
  HK: {
    code: 'HK',
    name: 'Hong Kong',
    currency: 'HKD',
    currencySymbol: 'HK$',
    currencyLocale: 'en-HK',
    taxSystem: 'None',
    taxIdLabel: 'Business Registration Number',
    taxIdPlaceholder: 'e.g. 12345678-000-00-00-0',
    taxIdMaxLength: 20,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: null, // No tax invoice concept in HK
    hasTaxInvoice: false,
    taxRates: [],
    defaultTaxRate: 0,
    supportsCustomTaxRate: false,
    taxBreakdown: 'none',
    regionType: null,
    regionLabel: null,
    regions: [],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName'],
    optionalFields: ['firmAddress', 'firmPhone', 'firmEmail', 'taxId', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice No.',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal',
      discount: 'Discount',
      taxLine: null,
      total: 'Total',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── MALAYSIA ─────────────────────────────────────────────────────────
  MY: {
    code: 'MY',
    name: 'Malaysia',
    currency: 'MYR',
    currencySymbol: 'RM',
    currencyLocale: 'ms-MY',
    taxSystem: 'SST (Sales & Service Tax)',
    taxIdLabel: 'SST Registration Number',
    taxIdPlaceholder: 'e.g. W10-1234-56789012',
    taxIdMaxLength: 20,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'Tax Invoice',
    taxRates: [
      { label: 'Service Tax (8%)', rate: 8 },
      { label: 'Sales Tax (10%)', rate: 10 },
      { label: 'Sales Tax (5%)', rate: 5 },
      { label: 'Exempt (0%)', rate: 0 },
    ],
    defaultTaxRate: 8,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: 'state',
    regionLabel: 'State',
    regions: [
      'Johor', 'Kedah', 'Kelantan', 'Kuala Lumpur', 'Labuan', 'Melaka', 'Negeri Sembilan',
      'Pahang', 'Penang', 'Perak', 'Perlis', 'Putrajaya', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu',
    ],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    extraFields: [
      { key: 'tin', label: 'TIN (Tax Identification Number)', placeholder: 'e.g. C12345678000', maxLength: 14 },
    ],
    customerLabel: 'Customer',
    vendorLabel: 'Supplier',
    printTitle: { simple: 'INVOICE', tax: 'TAX INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice No.',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price (RM)',
      amount: 'Amount (RM)',
      subtotal: 'Subtotal',
      discount: 'Discount',
      taxLine: 'SST',
      total: 'Total (incl. SST)',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },

  // ─── NIGERIA ──────────────────────────────────────────────────────────
  NG: {
    code: 'NG',
    name: 'Nigeria',
    currency: 'NGN',
    currencySymbol: '₦',
    currencyLocale: 'en-NG',
    taxSystem: 'VAT',
    taxIdLabel: 'TIN (Tax Identification Number)',
    taxIdPlaceholder: 'e.g. 12345678-0001',
    taxIdMaxLength: 14,
    simpleInvoiceLabel: 'Invoice',
    taxInvoiceLabel: 'VAT Invoice',
    taxRates: [
      { label: 'Standard (7.5%)', rate: 7.5 },
      { label: 'Zero-rated (0%)', rate: 0 },
      { label: 'Exempt', rate: 0, exempt: true },
    ],
    defaultTaxRate: 7.5,
    supportsCustomTaxRate: false,
    taxBreakdown: 'single',
    regionType: 'state',
    regionLabel: 'State',
    regions: [
      'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
      'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT Abuja', 'Gombe',
      'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos',
      'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers',
      'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
    ],
    requiredFieldsSimple: ['firmName'],
    requiredFieldsTax: ['firmName', 'firmAddress', 'taxId'],
    optionalFields: ['firmPhone', 'firmEmail', 'bankDetails'],
    customerLabel: 'Customer',
    vendorLabel: 'Vendor',
    printTitle: { simple: 'INVOICE', tax: 'VAT INVOICE' },
    printLabels: {
      billTo: 'Bill To',
      shipTo: 'Ship To',
      invoiceNo: 'Invoice No.',
      invoiceDate: 'Date',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Qty',
      rate: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal',
      discount: 'Discount',
      taxLine: 'VAT (7.5%)',
      total: 'Total (incl. VAT)',
      amountDue: 'Amount Due',
      paymentTerms: 'Payment Terms',
      notes: 'Notes',
    },
  },
};

// ─── Helper exports ─────────────────────────────────────────────────────

// Sorted list of countries for dropdown
export const COUNTRIES = Object.values(COUNTRY_CONFIGS)
  .sort((a, b) => a.name.localeCompare(b.name))
  .map(c => ({ code: c.code, name: c.name, currency: c.currency, currencySymbol: c.currencySymbol }));

// Get full config for a country code
export function getCountryConfig(code) {
  return COUNTRY_CONFIGS[code] || COUNTRY_CONFIGS.IN; // default to India
}

// Check if a country uses existing India forms
export function usesExistingForms(code) {
  return COUNTRY_CONFIGS[code]?.useExistingForms === true;
}

// Check if a country has tax invoices
export function hasTaxInvoice(code) {
  const config = COUNTRY_CONFIGS[code];
  if (!config) return true;
  return config.hasTaxInvoice !== false;
}

// Format currency for a country
export function formatCountryCurrency(amount, countryCode) {
  const config = COUNTRY_CONFIGS[countryCode] || COUNTRY_CONFIGS.IN;
  try {
    return new Intl.NumberFormat(config.currencyLocale, {
      style: 'currency',
      currency: config.currency,
      maximumFractionDigits: config.currency === 'JPY' || config.currency === 'KRW' ? 0 : 2,
    }).format(amount);
  } catch {
    return `${config.currencySymbol}${Number(amount).toLocaleString()}`;
  }
}

// Calculate tax for line items based on country config
export function calculateCountryTax(lineItems, countryCode, invoiceType = 'simple') {
  const config = COUNTRY_CONFIGS[countryCode];
  if (!config || invoiceType === 'simple') {
    // Simple invoices: no tax
    const subtotal = lineItems.reduce((sum, item) => {
      const qty = parseFloat(item.quantity) || 0;
      const rate = parseFloat(item.rate) || 0;
      const discount = parseFloat(item.discount_percent) || 0;
      const lineTotal = qty * rate;
      const discountAmt = lineTotal * (discount / 100);
      return sum + (lineTotal - discountAmt);
    }, 0);
    return { subtotal, totalTax: 0, taxBreakdown: [], grandTotal: subtotal };
  }

  // Tax invoice: calculate per line item
  const taxBuckets = {};
  let subtotal = 0;
  let totalTax = 0;

  lineItems.forEach(item => {
    const qty = parseFloat(item.quantity) || 0;
    const rate = parseFloat(item.rate) || 0;
    const discount = parseFloat(item.discount_percent) || 0;
    const taxRate = parseFloat(item.tax_rate) || 0;
    const lineTotal = qty * rate;
    const discountAmt = lineTotal * (discount / 100);
    const taxableAmt = lineTotal - discountAmt;
    const taxAmt = taxableAmt * (taxRate / 100);

    subtotal += taxableAmt;
    totalTax += taxAmt;

    if (taxRate > 0) {
      const key = `${taxRate}`;
      if (!taxBuckets[key]) taxBuckets[key] = { rate: taxRate, taxable: 0, tax: 0 };
      taxBuckets[key].taxable += taxableAmt;
      taxBuckets[key].tax += taxAmt;
    }
  });

  const taxBreakdown = Object.values(taxBuckets).sort((a, b) => b.rate - a.rate);
  const grandTotal = Math.round((subtotal + totalTax) * 100) / 100;

  return { subtotal, totalTax, taxBreakdown, grandTotal };
}

export default COUNTRY_CONFIGS;
