import Foundation

enum AppStrings {
    static let strings: [String: [String: String]] = [
        // MARK: - Navigation / Tabs
        "dashboard": ["en": "Dashboard", "hi": "डैशबोर्ड"],
        "transactions": ["en": "Transactions", "hi": "लेन-देन"],
        "accounts": ["en": "Accounts", "hi": "खाते"],
        "reports": ["en": "Reports", "hi": "रिपोर्ट"],
        "more": ["en": "More", "hi": "और"],

        // MARK: - More Menu Sections & Items
        "finance": ["en": "Finance", "hi": "वित्त"],
        "people": ["en": "People", "hi": "लोग"],
        "obligations": ["en": "Obligations", "hi": "देनदारियाँ"],
        "data": ["en": "Data", "hi": "डेटा"],
        "tools": ["en": "Tools", "hi": "टूल्स"],
        "account_section": ["en": "Account", "hi": "खाता"],
        "cash_flow": ["en": "Cash Flow", "hi": "कैश फ्लो"],
        "invoices": ["en": "Invoices", "hi": "इनवॉइस"],
        "purchases": ["en": "Purchases", "hi": "खरीदारी"],
        "categories": ["en": "Categories", "hi": "श्रेणियाँ"],
        "customers": ["en": "Customers", "hi": "ग्राहक"],
        "vendors": ["en": "Vendors", "hi": "विक्रेता"],
        "mandates": ["en": "Mandates", "hi": "मैंडेट"],
        "reconciliation": ["en": "Reconciliation", "hi": "मिलान"],
        "email_sync": ["en": "Email Sync", "hi": "ईमेल सिंक"],
        "sms_sync": ["en": "SMS Sync", "hi": "SMS सिंक"],
        "records": ["en": "Records", "hi": "रिकॉर्ड"],
        "past_insights": ["en": "Past Insights", "hi": "पिछली जानकारी"],
        "ai_chat": ["en": "AI Chat", "hi": "AI चैट"],
        "feature_requests": ["en": "Feature Requests", "hi": "सुझाव"],
        "support": ["en": "Support", "hi": "सहायता"],
        "settings": ["en": "Settings", "hi": "सेटिंग्स"],
        "billing": ["en": "Billing", "hi": "बिलिंग"],

        // MARK: - Dashboard
        "net_worth": ["en": "Net Worth", "hi": "कुल संपत्ति"],
        "income_this_month": ["en": "Income This Month", "hi": "इस महीने की आय"],
        "expenses_this_month": ["en": "Expenses This Month", "hi": "इस महीने का खर्च"],
        "pending_approval": ["en": "Pending Approval", "hi": "स्वीकृति बाकी"],
        "upcoming_outflows": ["en": "Upcoming outflows next month", "hi": "अगले महीने के खर्चे"],
        "total_outflow": ["en": "Total Outflow", "hi": "कुल बहिर्वाह"],
        "syncing": ["en": "Syncing...", "hi": "सिंक हो रहा है..."],
        "no_pending": ["en": "No pending transactions", "hi": "कोई लंबित लेन-देन नहीं"],
        "all_caught_up": ["en": "All Caught Up", "hi": "सब अपडेट है"],
        "may_projection": ["en": "May Projection", "hi": "मई अनुमान"],
        "expenses": ["en": "Expenses", "hi": "खर्चे"],
        "emis": ["en": "EMIs", "hi": "EMIs"],
        "od_interest": ["en": "OD Interest", "hi": "OD ब्याज"],

        // MARK: - Common Buttons
        "cancel": ["en": "Cancel", "hi": "रद्द करें"],
        "done": ["en": "Done", "hi": "हो गया"],
        "ok": ["en": "OK", "hi": "ठीक है"],
        "save": ["en": "Save", "hi": "सेव करें"],
        "create": ["en": "Create", "hi": "बनाएँ"],
        "delete": ["en": "Delete", "hi": "हटाएँ"],
        "edit": ["en": "Edit", "hi": "बदलें"],
        "select": ["en": "Select", "hi": "चुनें"],
        "none_option": ["en": "None", "hi": "कोई नहीं"],
        "apply": ["en": "Apply", "hi": "लागू करें"],
        "close": ["en": "Close", "hi": "बंद करें"],
        "retry": ["en": "Retry", "hi": "फिर कोशिश करें"],
        "submit": ["en": "Submit", "hi": "जमा करें"],
        "approve": ["en": "Approve", "hi": "स्वीकार करें"],
        "reject": ["en": "Reject", "hi": "अस्वीकार करें"],
        "search": ["en": "Search", "hi": "खोजें"],
        "add": ["en": "Add", "hi": "जोड़ें"],
        "confirm": ["en": "Confirm", "hi": "पुष्टि करें"],
        "select_all": ["en": "Select All", "hi": "सभी चुनें"],
        "deselect": ["en": "Deselect", "hi": "अचयनित करें"],
        "approve_all": ["en": "Approve All", "hi": "सभी स्वीकार करें"],
        "reject_all": ["en": "Reject All", "hi": "सभी अस्वीकार करें"],
        "sign_out": ["en": "Sign Out", "hi": "साइन आउट"],
        "subscribe": ["en": "Subscribe", "hi": "सदस्यता लें"],
        "validate": ["en": "Validate", "hi": "जाँचें"],

        // MARK: - Transaction Form
        "amount": ["en": "Amount", "hi": "राशि"],
        "money_spent": ["en": "Money spent", "hi": "खर्च की गई राशि"],
        "money_received": ["en": "Money received", "hi": "प्राप्त राशि"],
        "details": ["en": "Details", "hi": "विवरण"],
        "date": ["en": "Date", "hi": "तारीख"],
        "account_label": ["en": "Account", "hi": "खाता"],
        "payment": ["en": "Payment", "hi": "भुगतान"],
        "category": ["en": "Category", "hi": "श्रेणी"],
        "subcategory": ["en": "Subcategory", "hi": "उप-श्रेणी"],
        "note": ["en": "Note", "hi": "नोट"],
        "add_note": ["en": "Add a note...", "hi": "नोट लिखें..."],
        "recurring": ["en": "Recurring", "hi": "बार-बार होने वाला"],
        "repeat_toggle": ["en": "Repeat", "hi": "दोहराएँ"],
        "frequency": ["en": "Frequency", "hi": "कितनी बार"],
        "daily": ["en": "Daily", "hi": "रोज़ाना"],
        "weekly": ["en": "Weekly", "hi": "साप्ताहिक"],
        "monthly": ["en": "Monthly", "hi": "मासिक"],
        "quarterly": ["en": "Quarterly", "hi": "तिमाही"],
        "yearly": ["en": "Yearly", "hi": "वार्षिक"],
        "attachment": ["en": "Attachment", "hi": "अटैचमेंट"],
        "receipt": ["en": "Receipt", "hi": "रसीद"],
        "take_photo": ["en": "Take Photo", "hi": "फोटो लें"],
        "choose_photo": ["en": "Choose Photo", "hi": "फोटो चुनें"],
        "receipt_attached": ["en": "Receipt attached", "hi": "रसीद जुड़ी है"],
        "scanning_receipt": ["en": "Scanning receipt...", "hi": "रसीद स्कैन हो रही है..."],
        "source_document": ["en": "Source Document", "hi": "स्रोत दस्तावेज़"],
        "no_source": ["en": "No source content available", "hi": "स्रोत उपलब्ध नहीं"],
        "loading_source": ["en": "Loading source...", "hi": "स्रोत लोड हो रहा है..."],
        "switch_to_invoice": ["en": "Switch to Invoice", "hi": "इनवॉइस पर जाएँ"],
        "missing_info": ["en": "Missing Information", "hi": "जानकारी अधूरी है"],
        "income": ["en": "Income", "hi": "आय"],
        "expense": ["en": "Expense", "hi": "खर्च"],
        "transfer": ["en": "Transfer", "hi": "ट्रांसफर"],
        "new_transaction": ["en": "New Transaction", "hi": "नया लेन-देन"],
        "edit_transaction": ["en": "Edit Transaction", "hi": "लेन-देन बदलें"],
        "add_transaction": ["en": "Add Transaction", "hi": "लेन-देन जोड़ें"],
        "delete_transaction": ["en": "Delete Transaction", "hi": "लेन-देन हटाएँ"],
        "approve_transaction": ["en": "Approve Transaction", "hi": "लेन-देन स्वीकार करें"],
        "reject_transaction": ["en": "Reject Transaction", "hi": "लेन-देन अस्वीकार करें"],
        "transaction_details": ["en": "Transaction Details", "hi": "लेन-देन का विवरण"],
        "review_transaction": ["en": "Review Transaction", "hi": "लेन-देन की समीक्षा"],
        "description": ["en": "Description", "hi": "विवरण"],
        "transaction_description": ["en": "Transaction description", "hi": "लेन-देन का विवरण"],
        "view_receipt": ["en": "View Receipt", "hi": "रसीद देखें"],
        "no_receipt": ["en": "No receipt attached", "hi": "कोई रसीद नहीं"],
        "receipt_preview_future": ["en": "Full receipt preview will be available in a future update.", "hi": "रसीद का पूरा प्रीव्यू भविष्य के अपडेट में उपलब्ध होगा।"],

        // MARK: - Transactions List
        "no_approved_transactions": ["en": "No Approved Transactions", "hi": "कोई स्वीकृत लेन-देन नहीं"],
        "pending_review_count": ["en": "You have %d transactions pending review.", "hi": "आपके %d लेन-देन समीक्षा के लिए बाकी हैं।"],
        "no_transactions": ["en": "No Transactions", "hi": "कोई लेन-देन नहीं"],
        "search_transactions": ["en": "Search transactions...", "hi": "लेन-देन खोजें..."],
        "all_accounts": ["en": "All Accounts", "hi": "सभी खाते"],
        "date_range": ["en": "Date Range", "hi": "तारीख सीमा"],
        "from": ["en": "From", "hi": "से"],
        "to": ["en": "To", "hi": "तक"],
        "list": ["en": "List", "hi": "सूची"],
        "ledger": ["en": "Ledger", "hi": "खाता बही"],
        "cannot_undo": ["en": "This action cannot be undone.", "hi": "यह कार्य पूर्ववत नहीं किया जा सकता।"],

        // MARK: - Ledger
        "select_account_ledger": ["en": "Select an account to see running balance", "hi": "चालू शेष देखने के लिए खाता चुनें"],
        "debit": ["en": "Debit", "hi": "नामे (डेबिट)"],
        "credit": ["en": "Credit", "hi": "जमा (क्रेडिट)"],
        "balance": ["en": "Balance", "hi": "शेष"],

        // MARK: - Accounts
        "total_balance": ["en": "Total Balance", "hi": "कुल शेष"],
        "search_accounts": ["en": "Search accounts", "hi": "खाते खोजें"],
        "asset": ["en": "Asset", "hi": "संपत्ति"],
        "liability": ["en": "Liability", "hi": "देनदारी"],
        "current_balance": ["en": "Current Balance", "hi": "वर्तमान शेष"],
        "set_opening_balance": ["en": "Set Opening Balance", "hi": "शुरुआती शेष सेट करें"],
        "opening_balance": ["en": "Opening Balance", "hi": "शुरुआती शेष"],
        "not_set_tap": ["en": "Not set — tap to add", "hi": "सेट नहीं है — जोड़ने के लिए टैप करें"],
        "as_of_date": ["en": "As-of Date", "hi": "तारीख के अनुसार"],
        "balance_recalc_info": ["en": "Balance will be recalculated: opening balance + income - expenses +/- transfers from this date onward.", "hi": "शेष की पुनर्गणना होगी: शुरुआती शेष + आय - खर्च +/- ट्रांसफर इस तारीख से आगे।"],
        "clear_filters": ["en": "Clear Filters", "hi": "फ़िल्टर हटाएँ"],
        "more_filters": ["en": "More Filters", "hi": "और फ़िल्टर"],
        "all_categories": ["en": "All Categories", "hi": "सभी श्रेणियाँ"],
        "min_amount": ["en": "Min Amount", "hi": "न्यूनतम राशि"],
        "max_amount": ["en": "Max Amount", "hi": "अधिकतम राशि"],
        "no_limit": ["en": "No limit", "hi": "कोई सीमा नहीं"],
        "apply_filters": ["en": "Apply Filters", "hi": "फ़िल्टर लागू करें"],
        "amortization_schedule": ["en": "Amortization Schedule", "hi": "किस्त अनुसूची"],
        "loading_schedule": ["en": "Loading schedule...", "hi": "अनुसूची लोड हो रही है..."],
        "principal": ["en": "Principal", "hi": "मूलधन"],
        "interest": ["en": "Interest", "hi": "ब्याज"],
        "od_interest_calculator": ["en": "OD Interest Calculator", "hi": "OD ब्याज कैलकुलेटर"],
        "calculate_interest": ["en": "Calculate Interest", "hi": "ब्याज गणना करें"],
        "account_name_placeholder": ["en": "Account Name", "hi": "खाते का नाम"],
        "sub_type": ["en": "Sub-Type", "hi": "उप-प्रकार"],
        "account_number": ["en": "Account Number", "hi": "खाता संख्या"],
        "basic_info": ["en": "Basic Information", "hi": "मूल जानकारी"],
        "loan_details": ["en": "Loan Details", "hi": "लोन विवरण"],
        "broker_name": ["en": "Broker Name", "hi": "ब्रोकर का नाम"],
        "demat_details": ["en": "Demat Details", "hi": "डीमैट विवरण"],
        "notes": ["en": "Notes", "hi": "नोट्स"],
        "new_account": ["en": "New Account", "hi": "नया खाता"],
        "new_category": ["en": "New Category", "hi": "नई श्रेणी"],
        "new_subcategory": ["en": "New Subcategory", "hi": "नई उप-श्रेणी"],
        "enter_account_name": ["en": "Enter a name and type for the new account.", "hi": "नए खाते का नाम और प्रकार डालें।"],
        "enter_subcategory_name": ["en": "Enter a name for the new subcategory.", "hi": "नई उप-श्रेणी का नाम डालें।"],
        "no_accounts": ["en": "No Accounts", "hi": "कोई खाता नहीं"],
        "no_accounts_found": ["en": "No accounts found", "hi": "कोई खाता नहीं मिला"],

        // MARK: - Account Types
        "savings": ["en": "Savings", "hi": "बचत"],
        "current": ["en": "Current", "hi": "चालू"],
        "credit_card": ["en": "Credit Card", "hi": "क्रेडिट कार्ड"],
        "cash": ["en": "Cash", "hi": "नकद"],
        "wallet": ["en": "Wallet", "hi": "वॉलेट"],
        "loan": ["en": "Loan", "hi": "लोन"],
        "investment": ["en": "Investment", "hi": "निवेश"],
        "bank": ["en": "Bank", "hi": "बैंक"],
        "digital_wallet": ["en": "Digital Wallet", "hi": "डिजिटल वॉलेट"],

        // MARK: - Reports
        "total_income": ["en": "Total Income", "hi": "कुल आय"],
        "total_expense": ["en": "Total Expense", "hi": "कुल खर्च"],
        "net": ["en": "Net", "hi": "शुद्ध"],
        "category_details": ["en": "Category Details", "hi": "श्रेणी विवरण"],
        "no_categories_display": ["en": "No categories to display", "hi": "कोई श्रेणी नहीं"],
        "view_all_transactions": ["en": "View all transactions", "hi": "सभी लेन-देन देखें"],
        "export_csv": ["en": "Export CSV", "hi": "CSV डाउनलोड करें"],
        "export_pdf": ["en": "Export PDF", "hi": "PDF डाउनलोड करें"],
        "no_transactions_found": ["en": "No transactions found", "hi": "कोई लेन-देन नहीं मिला"],
        "by_category": ["en": "By Category", "hi": "श्रेणी अनुसार"],
        "no_category_data": ["en": "No category data", "hi": "श्रेणी डेटा नहीं"],
        "total": ["en": "Total", "hi": "कुल"],
        "income_vs_expense": ["en": "Income vs Expense", "hi": "आय बनाम खर्च"],
        "no_data_period": ["en": "No data for this period", "hi": "इस अवधि का डेटा नहीं है"],
        "this_month": ["en": "This Month", "hi": "इस महीने"],
        "last_3_months": ["en": "Last 3 Months", "hi": "पिछले 3 महीने"],
        "last_6_months": ["en": "Last 6 Months", "hi": "पिछले 6 महीने"],
        "this_year": ["en": "This Year", "hi": "इस साल"],

        // MARK: - Cash Flow
        "monthly_breakdown": ["en": "Monthly Breakdown", "hi": "मासिक ब्यौरा"],
        "recurring_expenses": ["en": "Recurring Expenses", "hi": "बार-बार होने वाले खर्चे"],
        "total_monthly_emi": ["en": "Total Monthly EMI", "hi": "कुल मासिक EMI"],
        "net_cash_flow": ["en": "Net Cash Flow", "hi": "शुद्ध कैश फ्लो"],
        "view_source_doc": ["en": "View Source Document", "hi": "स्रोत दस्तावेज़ देखें"],
        "view_latest_txn": ["en": "View Latest Transaction", "hi": "अंतिम लेन-देन देखें"],
        "edit_mandate": ["en": "Edit Mandate", "hi": "मैंडेट बदलें"],
        "delete_mandate": ["en": "Delete Mandate", "hi": "मैंडेट हटाएँ"],
        "delete_mandate_confirm": ["en": "Are you sure you want to delete this mandate? This will update your cash flow projections.", "hi": "क्या आप यह मैंडेट हटाना चाहते हैं? इससे कैश फ्लो अनुमान बदल जाएगा।"],
        "no_source_doc": ["en": "No source document available", "hi": "स्रोत दस्तावेज़ उपलब्ध नहीं"],
        "merchant_payee": ["en": "Merchant / Payee", "hi": "व्यापारी / प्राप्तकर्ता"],
        "merchant_name": ["en": "Merchant name", "hi": "व्यापारी का नाम"],
        "mandate_type": ["en": "Mandate Type", "hi": "मैंडेट प्रकार"],
        "subscription": ["en": "Subscription", "hi": "सदस्यता"],
        "emi": ["en": "EMI", "hi": "EMI"],
        "insurance": ["en": "Insurance", "hi": "बीमा"],
        "utility": ["en": "Utility", "hi": "उपयोगिता"],
        "other": ["en": "Other", "hi": "अन्य"],
        "status": ["en": "Status", "hi": "स्थिति"],
        "active": ["en": "Active", "hi": "सक्रिय"],
        "paused": ["en": "Paused", "hi": "रुका हुआ"],
        "cancelled": ["en": "Cancelled", "hi": "रद्द"],
        "monthly_emi": ["en": "Monthly EMI", "hi": "मासिक EMI"],
        "monthly_interest_charge": ["en": "Monthly Interest Charge", "hi": "मासिक ब्याज शुल्क"],
        "projection_24m": ["en": "24-Month Projection", "hi": "24 महीने का अनुमान"],
        "no_projection_data": ["en": "No projection data yet", "hi": "अनुमान डेटा अभी नहीं है"],
        "no_recurring_income": ["en": "No recurring income items found", "hi": "कोई बार-बार होने वाली आय नहीं मिली"],
        "no_recurring_expense": ["en": "No recurring expense items found", "hi": "कोई बार-बार होने वाला खर्च नहीं मिला"],
        "no_active_mandates": ["en": "No active mandates", "hi": "कोई सक्रिय मैंडेट नहीं"],
        "no_od_interest": ["en": "No overdraft interest charges", "hi": "कोई ओवरड्राफ्ट ब्याज नहीं"],
        "no_active_emis": ["en": "No active EMIs", "hi": "कोई सक्रिय EMI नहीं"],
        "view_calendar": ["en": "View day-wise cash flow calendar", "hi": "दैनिक कैश फ्लो कैलेंडर देखें"],
        "recurring_transactions": ["en": "Recurring Transactions", "hi": "बार-बार होने वाले लेन-देन"],
        "no_recurring_txns": ["en": "No recurring transactions", "hi": "कोई बार-बार होने वाला लेन-देन नहीं"],
        "mark_recurring_info": ["en": "Mark transactions as recurring to see them here", "hi": "यहाँ देखने के लिए लेन-देन को बार-बार होने वाला चिह्नित करें"],
        "no_fixed_date": ["en": "No Fixed Date", "hi": "कोई निश्चित तारीख नहीं"],
        "loading_transaction": ["en": "Loading transaction...", "hi": "लेन-देन लोड हो रहा है..."],
        "mandates_info": ["en": "Scans your past transactions to find recurring payments like subscriptions, EMIs, and auto-pay. Detected mandates improve your cash flow forecast.", "hi": "आपके पिछले लेन-देन से सदस्यता, EMI और ऑटो-पे जैसे बार-बार होने वाले भुगतान खोजता है। पाए गए मैंडेट कैश फ्लो अनुमान सुधारते हैं।"],
        "no_mandates_found": ["en": "No mandates found", "hi": "कोई मैंडेट नहीं मिला"],

        // MARK: - Invoices
        "invoice_number": ["en": "Invoice #", "hi": "इनवॉइस #"],
        "invoice": ["en": "Invoice", "hi": "इनवॉइस"],
        "customer": ["en": "Customer", "hi": "ग्राहक"],
        "customer_required": ["en": "Customer is required.", "hi": "ग्राहक आवश्यक है।"],
        "dates": ["en": "Dates", "hi": "तारीखें"],
        "line_items": ["en": "Line Items", "hi": "आइटम सूची"],
        "at_least_one_item": ["en": "At least one line item is required.", "hi": "कम से कम एक आइटम ज़रूरी है।"],
        "description_required": ["en": "Description is required.", "hi": "विवरण आवश्यक है।"],
        "qty": ["en": "Qty", "hi": "मात्रा"],
        "gst_percent": ["en": "GST %", "hi": "GST %"],
        "subtotal": ["en": "Subtotal", "hi": "उप-योग"],
        "igst": ["en": "IGST", "hi": "IGST"],
        "cgst": ["en": "CGST", "hi": "CGST"],
        "sgst": ["en": "SGST", "hi": "SGST"],
        "total_tax": ["en": "Total Tax", "hi": "कुल कर"],
        "grand_total": ["en": "Grand Total", "hi": "कुल योग"],
        "gst_summary": ["en": "GST Summary", "hi": "GST सारांश"],
        "payment_terms": ["en": "Payment Terms", "hi": "भुगतान शर्तें"],
        "terms_notes": ["en": "Terms & Notes", "hi": "शर्तें और नोट्स"],
        "search_invoice": ["en": "Search by number or customer", "hi": "नंबर या ग्राहक से खोजें"],
        "loading_invoice_pdf": ["en": "Loading invoice PDF...", "hi": "इनवॉइस PDF लोड हो रही है..."],
        "actions": ["en": "Actions", "hi": "कार्रवाई"],
        "delete_invoice_confirm": ["en": "Are you sure you want to delete this invoice? This action cannot be undone.", "hi": "क्या आप यह इनवॉइस हटाना चाहते हैं? यह पूर्ववत नहीं होगा।"],
        "could_not_load_pdf": ["en": "Could not load PDF", "hi": "PDF लोड नहीं हो सकी"],
        "no_invoices_match": ["en": "No invoices match your filters.", "hi": "आपके फ़िल्टर से कोई इनवॉइस मेल नहीं खाता।"],
        "debtors_summary": ["en": "Debtors Summary", "hi": "देनदार सारांश"],
        "aging_analysis": ["en": "Aging Analysis", "hi": "उम्र विश्लेषण"],
        "record_payment": ["en": "Record Payment", "hi": "भुगतान दर्ज करें"],
        "invoice_summary": ["en": "Invoice Summary", "hi": "इनवॉइस सारांश"],
        "invoice_total": ["en": "Invoice Total", "hi": "इनवॉइस कुल"],
        "amount_paid": ["en": "Amount Paid", "hi": "भुगतान की गई राशि"],
        "balance_due": ["en": "Balance Due", "hi": "बकाया शेष"],
        "payment_details": ["en": "Payment Details", "hi": "भुगतान विवरण"],
        "no_accounts_loaded": ["en": "No accounts loaded", "hi": "कोई खाता लोड नहीं"],
        "select_account": ["en": "Select Account", "hi": "खाता चुनें"],
        "deposit_account": ["en": "Deposit Account", "hi": "जमा खाता"],
        "deposit_account_info": ["en": "Select the bank/cash account where this payment was received.", "hi": "वह बैंक/नकद खाता चुनें जहाँ भुगतान प्राप्त हुआ।"],
        "payment_notes": ["en": "Payment notes (optional)", "hi": "भुगतान नोट (वैकल्पिक)"],
        "amount_greater_zero": ["en": "Amount must be greater than zero.", "hi": "राशि शून्य से अधिक होनी चाहिए।"],
        "no_invoices": ["en": "No Invoices Yet", "hi": "अभी कोई इनवॉइस नहीं"],
        "create_invoice": ["en": "Create Invoice", "hi": "इनवॉइस बनाएँ"],

        // MARK: - Purchases
        "bill_number": ["en": "Bill #", "hi": "बिल #"],
        "vendor": ["en": "Vendor", "hi": "विक्रेता"],
        "vendor_required": ["en": "Vendor is required.", "hi": "विक्रेता आवश्यक है।"],
        "tax_percent": ["en": "Tax %", "hi": "कर %"],
        "tax": ["en": "Tax", "hi": "कर"],
        "search_bills": ["en": "Search bills...", "hi": "बिल खोजें..."],
        "creditors": ["en": "Creditors", "hi": "लेनदार"],
        "no_bills": ["en": "No Bills Yet", "hi": "अभी कोई बिल नहीं"],
        "loading_bill_pdf": ["en": "Loading bill PDF...", "hi": "बिल PDF लोड हो रही है..."],
        "unable_load_pdf": ["en": "Unable to load PDF", "hi": "PDF लोड नहीं हो सकी"],
        "bill_preview_error": ["en": "The bill preview could not be generated.", "hi": "बिल प्रीव्यू नहीं बन सका।"],
        "bill_preview": ["en": "Bill Preview", "hi": "बिल प्रीव्यू"],
        "upload_bill": ["en": "Upload Bill", "hi": "बिल अपलोड करें"],
        "upload_bill_title": ["en": "Upload a Bill", "hi": "बिल अपलोड करें"],
        "upload_bill_info": ["en": "Upload a photo or PDF of a purchase bill. AI will extract the vendor, items, and amounts automatically.", "hi": "खरीदारी बिल की फोटो या PDF अपलोड करें। AI विक्रेता, आइटम और राशि अपने आप निकालेगा।"],
        "parsing_bill": ["en": "Parsing bill...", "hi": "बिल पढ़ा जा रहा है..."],
        "ai_extracting": ["en": "AI is extracting data from your bill. This may take a moment.", "hi": "AI आपके बिल से डेटा निकाल रहा है। इसमें कुछ समय लग सकता है।"],
        "bill_parsed": ["en": "Bill Parsed Successfully", "hi": "बिल सफलतापूर्वक पढ़ा गया"],
        "upload_another": ["en": "Upload Another", "hi": "और अपलोड करें"],
        "bill_summary": ["en": "Bill Summary", "hi": "बिल सारांश"],
        "bill_total": ["en": "Bill Total", "hi": "बिल कुल"],
        "delete_bill_confirm": ["en": "Are you sure you want to delete this bill? This cannot be undone.", "hi": "क्या आप यह बिल हटाना चाहते हैं? यह पूर्ववत नहीं होगा।"],

        // MARK: - Categories
        "expense_tab": ["en": "Expense", "hi": "खर्च"],
        "income_tab": ["en": "Income", "hi": "आय"],
        "add_subcategory": ["en": "Add Subcategory", "hi": "उप-श्रेणी जोड़ें"],
        "name": ["en": "Name", "hi": "नाम"],
        "none_top_level": ["en": "None (top-level)", "hi": "कोई नहीं (मुख्य)"],
        "parent": ["en": "Parent", "hi": "मुख्य श्रेणी"],
        "leave_empty_info": ["en": "Leave empty to create a top-level category.", "hi": "मुख्य श्रेणी बनाने के लिए खाली छोड़ें।"],
        "type": ["en": "Type", "hi": "प्रकार"],

        // MARK: - Customers
        "search_customers": ["en": "Search by name or email", "hi": "नाम या ईमेल से खोजें"],
        "customer_name": ["en": "Customer Name *", "hi": "ग्राहक का नाम *"],
        "name_required": ["en": "Name is required.", "hi": "नाम आवश्यक है।"],
        "required": ["en": "Required", "hi": "आवश्यक"],
        "email": ["en": "Email", "hi": "ईमेल"],
        "phone": ["en": "Phone", "hi": "फ़ोन"],
        "gstin": ["en": "GSTIN", "hi": "GSTIN"],
        "contact": ["en": "Contact", "hi": "संपर्क"],
        "billing_address": ["en": "Billing Address", "hi": "बिलिंग पता"],
        "shipping_address": ["en": "Shipping Address", "hi": "डिलीवरी पता"],
        "addresses": ["en": "Addresses", "hi": "पते"],
        "no_invoices_customer": ["en": "No invoices found for this customer.", "hi": "इस ग्राहक का कोई इनवॉइस नहीं मिला।"],

        // MARK: - Vendors
        "search_vendors": ["en": "Search vendors", "hi": "विक्रेता खोजें"],
        "vendor_name": ["en": "Vendor Name", "hi": "विक्रेता का नाम"],
        "business": ["en": "Business", "hi": "व्यापार"],
        "address": ["en": "Address", "hi": "पता"],
        "no_contact_details": ["en": "No contact details added.", "hi": "कोई संपर्क विवरण नहीं जोड़ा गया।"],
        "financial_summary": ["en": "Financial Summary", "hi": "वित्तीय सारांश"],
        "bills": ["en": "Bills", "hi": "बिल"],
        "no_bills_found": ["en": "No bills found", "hi": "कोई बिल नहीं मिला"],

        // MARK: - Email Sync
        "setting_up_sync": ["en": "Setting up sync...", "hi": "सिंक सेट हो रहा है..."],
        "sync_overview": ["en": "Sync Overview", "hi": "सिंक सारांश"],
        "processing_emails": ["en": "Processing emails...", "hi": "ईमेल प्रोसेस हो रहे हैं..."],
        "ai_analyzing": ["en": "AI analyzing emails...", "hi": "AI ईमेल विश्लेषण कर रहा है..."],
        "ai_complete": ["en": "AI analysis complete", "hi": "AI विश्लेषण पूरा"],
        "no_emails_processed": ["en": "No emails processed yet", "hi": "अभी कोई ईमेल प्रोसेस नहीं हुआ"],
        "scanning_inbox": ["en": "SpentyAI is scanning your inbox. This may take a few minutes.", "hi": "SpentyAI आपका इनबॉक्स स्कैन कर रहा है। इसमें कुछ मिनट लग सकते हैं।"],
        "tap_sync_start": ["en": "Tap Sync on your account below to start scanning emails.", "hi": "ईमेल स्कैन शुरू करने के लिए नीचे अपने खाते पर सिंक दबाएँ।"],
        "gmail": ["en": "Gmail", "hi": "Gmail"],
        "no_gmail": ["en": "No Gmail accounts connected", "hi": "कोई Gmail खाता नहीं जुड़ा"],
        "outlook": ["en": "Outlook", "hi": "Outlook"],
        "connect_outlook": ["en": "Connect Outlook", "hi": "Outlook जोड़ें"],
        "add_outlook": ["en": "Add Outlook Account", "hi": "Outlook खाता जोड़ें"],
        "connect_outlook_info": ["en": "Connect your Outlook email for sync", "hi": "सिंक के लिए Outlook ईमेल जोड़ें"],
        "needs_reconnect": ["en": "This account needs to be reconnected", "hi": "इस खाते को फिर से जोड़ना होगा"],
        "reconnect": ["en": "Reconnect", "hi": "फिर जोड़ें"],
        "sync": ["en": "Sync", "hi": "सिंक"],
        "disconnect": ["en": "Disconnect", "hi": "डिस्कनेक्ट"],
        "needs_reconnect_status": ["en": "Needs Reconnect", "hi": "फिर जोड़ना ज़रूरी"],
        "processing_failed": ["en": "Processing failed", "hi": "प्रोसेसिंग विफल"],
        "up_to_date": ["en": "Up to date", "hi": "अपडेट है"],
        "tap_sync": ["en": "Tap Sync to start", "hi": "सिंक शुरू करने के लिए दबाएँ"],
        "never_synced": ["en": "Never synced", "hi": "कभी सिंक नहीं हुआ"],
        "ai_detected_txns": ["en": "AI-detected transactions awaiting your approval", "hi": "AI द्वारा पाए गए लेन-देन आपकी स्वीकृति की प्रतीक्षा में हैं"],
        "how_far_back": ["en": "How far back should we scan?", "hi": "हम कितना पीछे तक स्कैन करें?"],
        "pick_date_range": ["en": "Pick a time range and SpentyAI will scan your emails from that date onward to detect transactions.", "hi": "समय सीमा चुनें और SpentyAI उस तारीख से आगे के ईमेल स्कैन करके लेन-देन खोजेगा।"],
        "pick_custom_date": ["en": "Pick a custom date", "hi": "कस्टम तारीख चुनें"],
        "sync_start_date": ["en": "Sync Start Date", "hi": "सिंक शुरू तारीख"],
        "start_sync": ["en": "Start Sync", "hi": "सिंक शुरू करें"],
        "provider_connected": ["en": "Connected!", "hi": "जुड़ गया!"],
        "emails": ["en": "Emails", "hi": "ईमेल"],
        "analyzed": ["en": "Analyzed", "hi": "विश्लेषित"],
        "retry_failed": ["en": "Retry Failed Emails", "hi": "विफल ईमेल फिर कोशिश करें"],
        "add_another_gmail": ["en": "Add Another Gmail", "hi": "और Gmail जोड़ें"],

        // MARK: - Records
        "zip": ["en": "ZIP", "hi": "ZIP"],
        "linked": ["en": "Linked", "hi": "जुड़ा हुआ"],
        "upload_receipt": ["en": "Upload Receipt", "hi": "रसीद अपलोड करें"],
        "select_receipt": ["en": "Select Receipt Image", "hi": "रसीद इमेज चुनें"],
        "choose_library": ["en": "Choose from your photo library", "hi": "अपनी फोटो लाइब्रेरी से चुनें"],
        "change": ["en": "Change", "hi": "बदलें"],
        "ai_parsed_data": ["en": "AI Parsed Data", "hi": "AI द्वारा निकाला गया डेटा"],
        "items": ["en": "Items", "hi": "आइटम"],
        "link_transaction": ["en": "Link to Transaction", "hi": "लेन-देन से जोड़ें"],
        "transaction_id": ["en": "Transaction ID", "hi": "लेन-देन ID"],
        "link_btn": ["en": "Link Transaction", "hi": "लेन-देन जोड़ें"],
        "linked_to_txn": ["en": "Linked to transaction", "hi": "लेन-देन से जुड़ा"],
        "no_content": ["en": "No content available", "hi": "सामग्री उपलब्ध नहीं"],
        "delete_email_record": ["en": "This email record will be permanently deleted.", "hi": "यह ईमेल रिकॉर्ड स्थायी रूप से हटा दिया जाएगा।"],
        "delete_receipt": ["en": "This receipt will be permanently removed.", "hi": "यह रसीद स्थायी रूप से हटा दी जाएगी।"],

        // MARK: - Reconciliation
        "statement_details": ["en": "Statement Details", "hi": "स्टेटमेंट विवरण"],
        "mark_approved": ["en": "Mark this statement as approved?", "hi": "इस स्टेटमेंट को स्वीकृत करें?"],
        "mark_rejected": ["en": "Mark this statement as rejected?", "hi": "इस स्टेटमेंट को अस्वीकृत करें?"],
        "statement_approved": ["en": "Statement Approved", "hi": "स्टेटमेंट स्वीकृत"],
        "statement_rejected": ["en": "Statement Rejected", "hi": "स्टेटमेंट अस्वीकृत"],
        "audit_status": ["en": "Audit Status", "hi": "ऑडिट स्थिति"],
        "processing": ["en": "Processing", "hi": "प्रोसेसिंग"],
        "reconcile": ["en": "Reconcile", "hi": "मिलान करें"],
        "bulk_categorize": ["en": "Bulk Categorize", "hi": "एक साथ श्रेणी लगाएँ"],
        "reconciliation_results": ["en": "Reconciliation Results", "hi": "मिलान परिणाम"],
        "difference": ["en": "Difference", "hi": "अंतर"],
        "matched": ["en": "Matched", "hi": "मिलान हुआ"],
        "missing_from_ledger": ["en": "Missing from Ledger", "hi": "खाता बही में नहीं"],
        "missing_from_statement": ["en": "Missing from Statement", "hi": "स्टेटमेंट में नहीं"],
        "statement_col": ["en": "Statement", "hi": "स्टेटमेंट"],
        "ledger_col": ["en": "Ledger", "hi": "खाता बही"],
        "conflicts": ["en": "Conflicts", "hi": "विवाद"],
        "parsed_entries": ["en": "Parsed Entries", "hi": "पार्स की गई प्रविष्टियाँ"],
        "no_entries_parsed": ["en": "No entries parsed yet", "hi": "अभी कोई प्रविष्टि नहीं"],
        "unlock_pdf": ["en": "Unlock PDF", "hi": "PDF अनलॉक करें"],
        "unlock_pdf_info": ["en": "Enter the password to unlock this password-protected PDF statement.", "hi": "पासवर्ड-सुरक्षित PDF स्टेटमेंट खोलने के लिए पासवर्ड डालें।"],
        "unlock_statement": ["en": "Unlock Statement", "hi": "स्टेटमेंट अनलॉक करें"],
        "select_category": ["en": "Select Category", "hi": "श्रेणी चुनें"],
        "upload_statement": ["en": "Upload Statement", "hi": "स्टेटमेंट अपलोड करें"],
        "account_sub_type": ["en": "Account Sub-Type", "hi": "खाता उप-प्रकार"],
        "all_types": ["en": "All Types", "hi": "सभी प्रकार"],
        "period_from": ["en": "Period From", "hi": "अवधि से"],
        "period_to": ["en": "Period To", "hi": "अवधि तक"],
        "statement_file": ["en": "Statement File", "hi": "स्टेटमेंट फ़ाइल"],
        "supported_formats": ["en": "Supported: PDF, CSV", "hi": "समर्थित: PDF, CSV"],

        // MARK: - AI Chat
        "ai_assistant": ["en": "AI Assistant", "hi": "AI सहायक"],
        "delete_history_confirm": ["en": "This will permanently delete your entire conversation history with the AI assistant.", "hi": "यह AI सहायक के साथ आपकी पूरी बातचीत स्थायी रूप से हटा देगा।"],
        "speaking": ["en": "Speaking...", "hi": "बोल रहा है..."],
        "listening": ["en": "Listening...", "hi": "सुन रहा है..."],
        "thinking": ["en": "Thinking...", "hi": "सोच रहा है..."],
        "tap_to_speak": ["en": "Tap to speak", "hi": "बोलने के लिए दबाएँ"],
        "send": ["en": "Send", "hi": "भेजें"],
        "exit": ["en": "Exit", "hi": "बाहर जाएँ"],
        "spentyai_assistant": ["en": "SpentyAI Assistant", "hi": "SpentyAI सहायक"],
        "ask_anything": ["en": "Ask me anything about your finances, or let me help you create transactions, invoices, and bills.", "hi": "अपने वित्त के बारे में कुछ भी पूछें, या मुझे लेन-देन, इनवॉइस और बिल बनाने में मदद करने दें।"],
        "ask_spentyai": ["en": "Ask SpentyAI...", "hi": "SpentyAI से पूछें..."],
        "transaction_created": ["en": "Transaction Created", "hi": "लेन-देन बना"],
        "invoice_created": ["en": "Invoice Created", "hi": "इनवॉइस बना"],
        "bill_created": ["en": "Bill Created", "hi": "बिल बना"],

        // MARK: - Past Insights
        "loading_accounts": ["en": "Loading email accounts...", "hi": "ईमेल खाते लोड हो रहे हैं..."],
        "generate_insight": ["en": "Generate Past Insight Summary", "hi": "पिछला विश्लेषण सारांश बनाएँ"],
        "new_insight": ["en": "New Past Insight Summary", "hi": "नया विश्लेषण सारांश"],
        "past_insight_summary": ["en": "Past Insight Summary", "hi": "विश्लेषण सारांश"],
        "summary": ["en": "Summary", "hi": "सारांश"],

        // MARK: - Settings
        "business_profile": ["en": "Business Profile", "hi": "व्यापार प्रोफ़ाइल"],
        "currency_locale": ["en": "Currency & Locale", "hi": "मुद्रा और भाषा"],
        "upload_logo": ["en": "Upload Logo", "hi": "लोगो अपलोड करें"],
        "upload_signature": ["en": "Upload Signature", "hi": "हस्ताक्षर अपलोड करें"],
        "reset_data": ["en": "Reset Data", "hi": "डेटा रीसेट करें"],
        "reset_data_subtitle": ["en": "Start fresh — removes all your data", "hi": "नई शुरुआत — सारा डेटा हटाएँ"],
        "delete_account": ["en": "Delete Account", "hi": "खाता हटाएँ"],
        "reset_warning": ["en": "This action is permanent. All your data will be erased and cannot be recovered.", "hi": "यह स्थायी है। आपका सारा डेटा मिट जाएगा और वापस नहीं आएगा।"],
        "type_reset_instruction": ["en": "To make sure this isn't an accident, type RESET in the box above.", "hi": "दुर्घटना से बचने के लिए ऊपर RESET टाइप करें।"],
        "data_cleared": ["en": "All your data has been cleared. Default accounts and categories have been set up for you — you're starting fresh!", "hi": "आपका सारा डेटा हटा दिया गया है। आपके लिए डिफ़ॉल्ट खाते और श्रेणियाँ बना दिए गए हैं — नई शुरुआत!"],
        "type_reset": ["en": "Type RESET", "hi": "RESET टाइप करें"],
        "reset_all_data": ["en": "Reset All Data?", "hi": "सारा डेटा रीसेट करें?"],
        "type_reset_confirm": ["en": "Type RESET to Confirm", "hi": "पुष्टि के लिए RESET टाइप करें"],
        "data_reset_complete": ["en": "Data Reset Complete", "hi": "डेटा रीसेट पूरा"],
        "confirm_action": ["en": "Confirm Action", "hi": "कार्रवाई पुष्टि"],
        "reset_vs_delete": ["en": "Reset Data wipes your transactions and records but keeps your account. Delete Account removes everything permanently.", "hi": "डेटा रीसेट आपके लेन-देन और रिकॉर्ड मिटाता है पर खाता रखता है। खाता हटाएँ सब स्थायी रूप से मिटाता है।"],
        "firm_details": ["en": "Firm Details", "hi": "फर्म विवरण"],
        "tax_identifiers": ["en": "Tax Identifiers", "hi": "कर पहचानकर्ता"],
        "select_state": ["en": "Select State", "hi": "राज्य चुनें"],
        "select_country": ["en": "Select Country", "hi": "देश चुनें"],
        "location": ["en": "Location", "hi": "स्थान"],
        "firm_name": ["en": "Firm Name", "hi": "फर्म का नाम"],
        "pan": ["en": "PAN", "hi": "PAN"],
        "business_address": ["en": "Business Address", "hi": "व्यापार पता"],
        "profile_updated": ["en": "Your business profile has been updated.", "hi": "आपकी व्यापार प्रोफ़ाइल अपडेट हो गई है।"],
        "select_currency": ["en": "Select Currency", "hi": "मुद्रा चुनें"],
        "select_format": ["en": "Select Format", "hi": "फ़ॉर्मेट चुनें"],
        "currency_info": ["en": "This currency will be used as the default for new invoices and transactions.", "hi": "यह मुद्रा नए इनवॉइस और लेन-देन के लिए डिफ़ॉल्ट होगी।"],
        "currency": ["en": "Currency", "hi": "मुद्रा"],
        "date_format_info": ["en": "Dates on invoices and reports will use this format.", "hi": "इनवॉइस और रिपोर्ट में तारीखें इस फ़ॉर्मेट में दिखेंगी।"],
        "date_format": ["en": "Date Format", "hi": "तारीख फ़ॉर्मेट"],
        "currency_updated": ["en": "Currency and locale settings have been updated.", "hi": "मुद्रा और भाषा सेटिंग्स अपडेट हो गई हैं।"],

        // MARK: - Billing
        "cancel_sub_confirm": ["en": "Are you sure you want to cancel your subscription? You'll retain access until the end of your current billing period.", "hi": "क्या आप सदस्यता रद्द करना चाहते हैं? आपकी वर्तमान बिलिंग अवधि के अंत तक पहुँच बनी रहेगी।"],
        "active_subscription": ["en": "Active Subscription", "hi": "सक्रिय सदस्यता"],
        "choose_plan": ["en": "Choose a Plan", "hi": "योजना चुनें"],
        "promo_code": ["en": "Promo Code", "hi": "प्रोमो कोड"],
        "activate_promo": ["en": "Activate Promo Code", "hi": "प्रोमो कोड लागू करें"],
        "payment_history": ["en": "Payment History", "hi": "भुगतान इतिहास"],
        "see_all": ["en": "See All", "hi": "सभी देखें"],
        "cancel_subscription": ["en": "Cancel Subscription", "hi": "सदस्यता रद्द करें"],
        "no_payments": ["en": "No Payments Yet", "hi": "अभी कोई भुगतान नहीं"],
        "payment_history_info": ["en": "Your payment history will appear here once you subscribe.", "hi": "सदस्यता लेने के बाद भुगतान इतिहास यहाँ दिखेगा।"],

        // MARK: - Support
        "how_can_help": ["en": "How can we help?", "hi": "हम कैसे मदद कर सकते हैं?"],
        "submit_ticket_info": ["en": "Submit a ticket or browse our FAQ below.", "hi": "टिकट जमा करें या नीचे FAQ देखें।"],
        "subject": ["en": "Subject", "hi": "विषय"],
        "subject_placeholder": ["en": "Brief description of your issue", "hi": "अपनी समस्या का संक्षिप्त विवरण"],
        "priority": ["en": "Priority", "hi": "प्राथमिकता"],
        "message": ["en": "Message", "hi": "संदेश"],
        "describe_issue": ["en": "Describe your issue in detail...", "hi": "अपनी समस्या का विस्तार से वर्णन करें..."],
        "no_faq": ["en": "No FAQ items available.", "hi": "कोई FAQ उपलब्ध नहीं।"],
        "support_submitted": ["en": "We've received your support request and will get back to you shortly.", "hi": "हमें आपका सहायता अनुरोध मिल गया है और हम जल्दी ही जवाब देंगे।"],

        // MARK: - Feature Requests
        "title": ["en": "Title", "hi": "शीर्षक"],
        "title_info": ["en": "A short, descriptive title for your request.", "hi": "अपने अनुरोध का छोटा, वर्णनात्मक शीर्षक।"],
        "describe_feature": ["en": "Describe what you'd like to see...", "hi": "आप क्या देखना चाहते हैं वर्णन करें..."],
        "new_request": ["en": "New Request", "hi": "नया अनुरोध"],

        // MARK: - Onboarding Slider
        "onboarding_skip": ["en": "Skip", "hi": "छोड़ें"],
        "onboarding_next": ["en": "Next", "hi": "अगला"],
        "onboarding_get_started": ["en": "Get Started", "hi": "शुरू करें"],
        "onboarding_slide1_title": ["en": "Auto Email Tracking", "hi": "ऑटो ईमेल ट्रैकिंग"],
        "onboarding_slide1_desc": ["en": "SpentyAI automatically captures every expense and income from your emails — no manual entry needed.", "hi": "SpentyAI आपके ईमेल से हर खर्च और आय अपने आप रिकॉर्ड करता है — कोई मैन्युअल एंट्री नहीं।"],
        "onboarding_slide2_title": ["en": "AI-Powered Accounting", "hi": "एआई लेखा-जोखा"],
        "onboarding_slide2_desc": ["en": "No accounting knowledge required. Just talk to the AI and it handles your books for you.", "hi": "लेखांकन की जानकारी जरूरी नहीं। बस एआई से बात करें और वह आपका हिसाब-किताब संभाल लेगा।"],
        "onboarding_slide3_title": ["en": "Complete Dashboard", "hi": "पूरा डैशबोर्ड"],
        "onboarding_slide3_desc": ["en": "See all your accounts, balances, and financial activity in one clear, detailed overview.", "hi": "एक जगह अपने सभी खाते, शेष राशि और वित्तीय गतिविधि का स्पष्ट विवरण देखें।"],
        "onboarding_slide4_title": ["en": "AI Transaction Insights", "hi": "एआई लेन-देन जानकारी"],
        "onboarding_slide4_desc": ["en": "Ask anything about your finances. The AI gives you instant insights from your transaction history.", "hi": "अपने वित्त के बारे में कुछ भी पूछें। एआई आपके लेन-देन इतिहास से तुरंत जानकारी देता है।"],
        "onboarding_slide5_title": ["en": "Smart Reports", "hi": "स्मार्ट रिपोर्ट"],
        "onboarding_slide5_desc": ["en": "Always know where your money is going with detailed, visual reports by category and period.", "hi": "श्रेणी और अवधि के अनुसार विस्तृत रिपोर्ट से हमेशा जानें आपका पैसा कहाँ जा रहा है।"],
        "onboarding_slide6_title": ["en": "Mandate & Cash Flow", "hi": "मैंडेट और कैश फ्लो"],
        "onboarding_slide6_desc": ["en": "SpentyAI detects your subscriptions and mandates from emails and shows your next month's outflow.", "hi": "SpentyAI आपके ईमेल से सब्सक्रिप्शन और मैंडेट खोजता है और अगले महीने का खर्च दिखाता है।"],
        "onboarding_slide7_title": ["en": "Invoices & Vendors", "hi": "चालान और विक्रेता"],
        "onboarding_slide7_desc": ["en": "Create GST invoices with your logo. Track customers, vendors, and purchases all in one place.", "hi": "अपने लोगो के साथ GST चालान बनाएं। ग्राहक, विक्रेता और खरीद एक ही जगह ट्रैक करें।"],
        "onboarding_slide8_title": ["en": "Try Free for 7 Days", "hi": "7 दिन मुफ़्त आज़माएं"],
        "onboarding_slide8_desc": ["en": "Try SpentyAI free for 7 days — then decide if you want to pay. No commitment required.", "hi": "SpentyAI को 7 दिन मुफ़्त आज़माएं — फिर तय करें कि भुगतान करना है या नहीं। कोई बाध्यता नहीं।"],

        // MARK: - Auth / Login
        "spentyai": ["en": "SpentyAI", "hi": "SpentyAI"],
        "smart_spending": ["en": "Smart spending starts here", "hi": "स्मार्ट खर्च यहाँ शुरू होता है"],
        "sign_in_google": ["en": "Sign in with Google", "hi": "Google से साइन इन करें"],
        "sign_in_error": ["en": "Sign In Error", "hi": "साइन इन त्रुटि"],

        // MARK: - Subscription Paywall
        "unlock_premium": ["en": "Unlock SpentyAI Premium", "hi": "SpentyAI प्रीमियम अनलॉक करें"],
        "premium_subtitle": ["en": "Smart financial insights, AI-powered categorization, and complete control over your money.", "hi": "स्मार्ट वित्तीय जानकारी, AI-संचालित वर्गीकरण, और अपने पैसे पर पूरा नियंत्रण।"],
        "continue_btn": ["en": "Continue", "hi": "जारी रखें"],
        "have_promo": ["en": "Have a promo code?", "hi": "प्रोमो कोड है?"],
        "enter_code": ["en": "Enter code", "hi": "कोड डालें"],
        "apply_promo": ["en": "Apply", "hi": "लागू करें"],
        "activate_promo_btn": ["en": "Activate Promo", "hi": "प्रोमो लागू करें"],
        "auto_detect_sub": ["en": "Already have a subscription? It will be detected automatically.", "hi": "पहले से सदस्यता है? यह अपने आप पता चल जाएगी।"],
        "recurring_billing": ["en": "Recurring billing. Cancel anytime in Settings.", "hi": "बार-बार बिलिंग। सेटिंग्स में कभी भी रद्द करें।"],
        "restore_purchases": ["en": "Restore Purchases", "hi": "खरीदारी बहाल करें"],
        "processing_paywall": ["en": "Processing...", "hi": "प्रोसेसिंग..."],


        // MARK: - Additional Localization Keys
        "loading_cash_flow": ["en": "Loading cash flow...", "hi": "कैश फ्लो लोड हो रहा है..."],
        "monthly_income": ["en": "Monthly Income", "hi": "मासिक आय"],
        "monthly_expense": ["en": "Monthly Expense", "hi": "मासिक खर्च"],
        "projection": ["en": "Projection", "hi": "अनुमान"],
        "month_header": ["en": "Month", "hi": "महीना"],
        "od_interest_short": ["en": "OD Int.", "hi": "OD ब्या."],
        "monthly_income_items": ["en": "Monthly Income Items", "hi": "मासिक आय आइटम"],
        "monthly_expense_items": ["en": "Monthly Expense Items", "hi": "मासिक खर्च आइटम"],
        "od_interest_breakdown": ["en": "OD Interest Breakdown", "hi": "OD ब्याज विवरण"],
        "emi_schedule": ["en": "EMI Schedule", "hi": "EMI अनुसूची"],
        "recurring_income": ["en": "Recurring Income", "hi": "बार-बार होने वाली आय"],
        "recurring_expense": ["en": "Recurring Expense", "hi": "बार-बार होने वाला खर्च"],
        "mandate_details": ["en": "Mandate Details", "hi": "मैंडेट विवरण"],
        "emi_details": ["en": "EMI Details", "hi": "EMI विवरण"],
        "od_interest_details": ["en": "OD Interest Details", "hi": "OD ब्याज विवरण"],
        "bill_details": ["en": "Bill Details", "hi": "बिल विवरण"],
        "totals": ["en": "Totals", "hi": "कुल"],
        "select_customer": ["en": "Select Customer", "hi": "ग्राहक चुनें"],
        "select_vendor": ["en": "Select Vendor", "hi": "विक्रेता चुनें"],
        "new_invoice": ["en": "New Invoice", "hi": "नया इनवॉइस"],
        "edit_invoice": ["en": "Edit Invoice", "hi": "इनवॉइस बदलें"],
        "new_bill": ["en": "New Bill", "hi": "नया बिल"],
        "edit_bill": ["en": "Edit Bill", "hi": "बिल बदलें"],
        "new_customer": ["en": "New Customer", "hi": "नया ग्राहक"],
        "edit_customer": ["en": "Edit Customer", "hi": "ग्राहक बदलें"],
        "new_vendor": ["en": "New Vendor", "hi": "नया विक्रेता"],
        "edit_vendor": ["en": "Edit Vendor", "hi": "विक्रेता बदलें"],
        "edit_category": ["en": "Edit Category", "hi": "श्रेणी बदलें"],
        "no_customers": ["en": "No Customers Yet", "hi": "अभी कोई ग्राहक नहीं"],
        "no_vendors": ["en": "No Vendors", "hi": "कोई विक्रेता नहीं"],
        "no_statements": ["en": "No Statements", "hi": "कोई स्टेटमेंट नहीं"],
        "no_email_records": ["en": "No Email Records", "hi": "कोई ईमेल रिकॉर्ड नहीं"],
        "no_receipts": ["en": "No Receipts", "hi": "कोई रसीद नहीं"],
        "no_requests": ["en": "No Requests Yet", "hi": "अभी कोई अनुरोध नहीं"],
        "no_past_insights": ["en": "No Past Insight Summaries", "hi": "कोई विश्लेषण सारांश नहीं"],
        "detect_mandates": ["en": "Detect Mandates", "hi": "मैंडेट खोजें"],
        "customer_details": ["en": "Customer Details", "hi": "ग्राहक विवरण"],

        "invoice_number_required": ["en": "Invoice number is required.", "hi": "इनवॉइस नंबर आवश्यक है।"],

        // MARK: - Missing Keys (Localization Pass)
        "error": ["en": "Error", "hi": "त्रुटि"],
        "all": ["en": "All", "hi": "सभी"],
        "date_set": ["en": "Date Set", "hi": "तारीख चुनी"],
        "add_first_transaction": ["en": "Add your first transaction to start tracking.", "hi": "ट्रैकिंग शुरू करने के लिए पहला लेन-देन जोड़ें।"],
        "delete_transaction_confirm": ["en": "Are you sure you want to delete this transaction? This action cannot be undone.", "hi": "क्या आप यह लेन-देन हटाना चाहते हैं? यह पूर्ववत नहीं होगा।"],
        "to_account": ["en": "To Account", "hi": "जमा खाता"],
        "payment_method": ["en": "Payment Method", "hi": "भुगतान विधि"],
        "yes": ["en": "Yes", "hi": "हाँ"],
        "no": ["en": "No", "hi": "नहीं"],
        "original_currency": ["en": "Original Currency", "hi": "मूल मुद्रा"],
        "original_amount": ["en": "Original Amount", "hi": "मूल राशि"],
        "exchange_rate": ["en": "Exchange Rate", "hi": "विनिमय दर"],
        "exchange_rate_est": ["en": "Exchange Rate (Est.)", "hi": "विनिमय दर (अनु.)"],
        "sender": ["en": "Sender", "hi": "भेजने वाला"],
        "transfer_amount": ["en": "Transfer amount", "hi": "ट्रांसफर राशि"],
        "day": ["en": "Day", "hi": "दिन"],
        "fill_required_fields": ["en": "Please fill in all required fields.", "hi": "कृपया सभी आवश्यक फ़ील्ड भरें।"],
        "valid_amount_error": ["en": "Please enter a valid amount.", "hi": "कृपया सही राशि डालें।"],
        "select_account_error": ["en": "Please select an account.", "hi": "कृपया खाता चुनें।"],
        "select_category_error": ["en": "Please select a category.", "hi": "कृपया श्रेणी चुनें।"],
        "select_dest_account_error": ["en": "Please select a destination account.", "hi": "कृपया गंतव्य खाता चुनें।"],
        "enter_category_name": ["en": "Enter a name for the new category.", "hi": "नई श्रेणी का नाम डालें।"],
        "no_results": ["en": "No Results", "hi": "कोई परिणाम नहीं"],
        "add_first_account": ["en": "Add your first account to start tracking your finances.", "hi": "वित्त ट्रैकिंग शुरू करने के लिए पहला खाता जोड़ें।"],
        "add_account": ["en": "Add Account", "hi": "खाता जोड़ें"],
        "edit_account": ["en": "Edit Account", "hi": "खाता बदलें"],
        "account_type": ["en": "Account Type", "hi": "खाता प्रकार"],
        "description_notes": ["en": "Description / Notes", "hi": "विवरण / नोट्स"],
        "interest_rate_pct": ["en": "Interest Rate (%)", "hi": "ब्याज दर (%)"],
        "tenure_months": ["en": "Tenure (Months)", "hi": "अवधि (महीने)"],
        "emi_amount": ["en": "EMI Amount", "hi": "EMI राशि"],
        "emi_day": ["en": "EMI Day (1-31)", "hi": "EMI दिन (1-31)"],
        "sanctioned_amount": ["en": "Sanctioned Amount", "hi": "स्वीकृत राशि"],
        "saving": ["en": "Saving...", "hi": "सेव हो रहा है..."],
        "save_recalculate": ["en": "Save & Recalculate", "hi": "सेव करें और पुनर्गणना"],
        "attach_receipt": ["en": "Attach Receipt", "hi": "रसीद जोड़ें"],
        "receipt_selected": ["en": "Receipt Selected", "hi": "रसीद चुनी गई"],
        "photo_or_document": ["en": "Photo or document", "hi": "फोटो या दस्तावेज़"],
        "attachments": ["en": "Attachments", "hi": "अटैचमेंट"],
        "unknown": ["en": "Unknown", "hi": "अज्ञात"],
        "uncategorized": ["en": "Uncategorized", "hi": "अवर्गीकृत"],
        "loading_accounts_msg": ["en": "Loading accounts...", "hi": "खाते लोड हो रहे हैं..."],
        "loading_account": ["en": "Loading account...", "hi": "खाता लोड हो रहा है..."],
        "from_date": ["en": "From Date", "hi": "तारीख से"],
        "to_date": ["en": "To Date", "hi": "तारीख तक"],
        "no_description": ["en": "No description", "hi": "कोई विवरण नहीं"],
        "no_transactions_match_filters": ["en": "No transactions match your filters", "hi": "आपके फ़िल्टर से कोई लेन-देन मेल नहीं खाता"],
        "total_payment": ["en": "Total Payment", "hi": "कुल भुगतान"],
        "total_interest": ["en": "Total Interest", "hi": "कुल ब्याज"],
        "failed_load_form_data": ["en": "Failed to load form data", "hi": "फ़ॉर्म डेटा लोड नहीं हो सका"],
        "interest_amount": ["en": "Interest Amount", "hi": "ब्याज राशि"],
        "number_of_days": ["en": "Number of Days", "hi": "दिनों की संख्या"],
        "average_balance": ["en": "Average Balance", "hi": "औसत शेष"],
        "effective_rate": ["en": "Effective Rate", "hi": "प्रभावी दर"],

        // MARK: - Language Toggle
        "language_hindi": ["en": "हि", "hi": "हि"],
        "language_english": ["en": "En", "hi": "En"],

        // MARK: - Legal & Support (Settings)
        "legal_support": ["en": "Legal & Support", "hi": "क़ानूनी और सहायता"],
        "about_spentyai": ["en": "About SpentyAI", "hi": "SpentyAI के बारे में"],
        "help_center": ["en": "Help Center", "hi": "सहायता केंद्र"],
        "contact_support": ["en": "Contact Support", "hi": "सहायता से संपर्क करें"],
        "privacy_policy": ["en": "Privacy Policy", "hi": "गोपनीयता नीति"],
        "terms_of_service": ["en": "Terms of Service", "hi": "सेवा की शर्तें"],
        "refund_policy": ["en": "Refund & Cancellation", "hi": "रिफ़ंड और रद्दीकरण"],
        "app_version": ["en": "Version", "hi": "संस्करण"],
    ]
}
